### ISSUE TITLE
Error python installation

### ISSUE THREAD

**Issue by AvivSham** [mgbellemare/Arcade-Learning-Environment#425]
Hi all,
When running the following installation command: `pip install -e .`
I receive the following error:
```
ERROR: Command errored out with exit status 1:
     command: /cortex/users/aviv/envs/rela/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py'"'"'; __file__='"'"'/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/
    Complete output (56 lines):
    running develop
    running egg_info
    writing ale_py.egg-info/PKG-INFO
    writing dependency_links to ale_py.egg-info/dependency_links.txt
    writing entry points to ale_py.egg-info/entry_points.txt
    writing requirements to ale_py.egg-info/requires.txt
    writing top-level names to ale_py.egg-info/top_level.txt
    reading manifest file 'ale_py.egg-info/SOURCES.txt'
    adding license file 'LICENSE.md'
    writing manifest file 'ale_py.egg-info/SOURCES.txt'
    running build_ext
    CMake Error at CMakeLists.txt:39 (project):
      Running

       '/tmp/pip-build-env-a7gc_d_l/overlay/bin/ninja' '--version'

      failed with:

       No such file or directory


    -- Configuring incomplete, errors occurred!
    See also "/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py", line 143, in <module>
        cmdclass={"build_ext": CMakeBuild}
      File "/tmp/pip-build-env-5dgpic2l/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-5dgpic2l/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/tmp/pip-build-env-5dgpic2l/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-5dgpic2l/overlay/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/cortex/users/aviv/envs/rela/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py", line 102, in build_extension
        ["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp
      File "/cortex/users/aviv/envs/rela/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment', '-DCMAKE_BUILD_TYPE=Release', '-DPython3_EXECUTABLE=/cortex/users/aviv/envs/rela/bin/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/build/lib.linux-x86_64-3.7/ale_py/', '-DSDL_SUPPORT=ON', '-DSDL_DYNLOAD=ON', '-DBUILD_CPP_LIB=OFF', '-DBUILD_PYTHON_LIB=ON', '-GNinja']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cortex/users/aviv/envs/rela/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py'"'"'; __file__='"'"'/home/lab/avivshamsian/rela/atari/Arcade-Learning-Environment/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

How can I fix this issue? 
In addition, is the Docker file valid? Can we use it to launch a container with Arcade env already installed?

Last question: what is the difference between the C++ installation and the pythonic one, are they independent? (is the C++ installation is just used to make things faster but it is not mandatory?)

Cheers,
Aviv
@AvivNavon

**Comment by JesseFarebro** [comment]
A couple of things,

Develop mode (i.e., `pip install -e`) doesn't work, it's a known issue with setuptools and our directory structure (see https://github.com/pypa/setuptools/issues/230).

> How can I fix this issue?

You can simply `pip install .` or install the RC Python package from PyPI: `pip install ale-py`.

> In addition, is the Docker file valid? Can we use it to launch a container with Arcade env already installed?

We don't provide a Docker image, the `docker` subdirectory is meant to store custom Dockerfiles we use in our build system.

> Last question: what is the difference between the C++ installation and the pythonic one, are they independent? (is the C++ installation is just used to make things faster but it is not mandatory?)

The Python package uses the C++ library, it's essentially Python bindings for the ALE which is written in C++.


Hope that helps.

**Comment by AvivSham** [comment]
Let me see if I understand you correctly. If I manage to run `pip install ale-py` successfully then the package is installed as expected.

**Comment by JesseFarebro** [comment]
Yes, exactly. Let me know if you have any issues with the Python package.

**Comment by AvivSham** [comment]
Thank you very much!
