### ISSUE TITLE
Missing rlglue java-codec examples

### ISSUE THREAD

**Issue by ScareCrow1987** [mgbellemare/Arcade-Learning-Environment#47]
The java examples should include a rlglue integration example by codec, not only the FIFO. Personally having problems integrating ALE and RL-Glue using java.

**Comment by mhauskn** [comment]
Can you be more specific about the problems you -- Is there a specific error you were getting using the Java RL-Glue codec?

**Comment by ScareCrow1987** [comment]
I implemented AgentInterface and created an Experiment class following the Skeletons codec example. I run them and get this:

Experiment starting up!
RL-Glue Java Agent Codec Version: 2.07 (Build:804:805M)
	Connecting to 127.0.0.1 on port 4096...
RL-Glue Java Experiment Codec Version: 2.07 (Build:804:805M)
	Connecting to 127.0.0.1 on port 4096...
	Experiment Codec Connected
	Agent Codec Connected
        // ALE is also running in rlglue mode and it say is connected
Observation have 128 integer dimensions
Exception in thread "agent-thrd" java.lang.NoSuchMethodError: This version of the task spec does not support: getActionDim at org.rlcommunity.rlglue.codec.taskspec.TaskSpecDelegate.getActionDim(TaskSpecDelegate.java:204)
	at org.rlcommunity.rlglue.codec.taskspec.TaskSpec.getActionDim(TaskSpec.java:417)
	at ale.agents.RandomAgent.agent_init(RandomAgent.java:21)
	at org.rlcommunity.rlglue.codec.network.ClientAgent.onAgentInit(ClientAgent.java:58)
	at org.rlcommunity.rlglue.codec.network.ClientAgent.runAgentEventLoop(ClientAgent.java:189)
	at org.rlcommunity.rlglue.codec.util.AgentLoader.run(AgentLoader.java:128)
	at ale.gui.Experimenter$2$1.run(Experimenter.java:66)

I don't know if this was the correct way of implementing the ALE java agent ? But it seem, is not getting the Actions (also tried getNumContinuousActionDim and getNumDiscreteActionDim with same results), the observation (RAM) seem right and the reward are also null.

**Comment by mhauskn** [comment]
Can you share the RL-Glue java agent you're attempting to connect? It would help me debug if I could reproduce the error.

**Comment by mgbellemare** [comment]
Closing this issue. Suggestion noted, but we won't be providing a Java RL-Glue agent right now.
