### ISSUE TITLE
python 3.9.13 pip install gym[accept-rom-license] error

### ISSUE THREAD

**Issue by xiezhipeng-git** [mgbellemare/Arcade-Learning-Environment#477]
python 3.9.13 windows  pip install gym[accept-rom-license] error

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: gym[accept-rom-license] in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (0.23.1)
Requirement already satisfied: numpy>=1.18.0 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from gym[accept-rom-license]) (1.24.0)
Requirement already satisfied: gym-notices>=0.0.4 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from gym[accept-rom-license]) (0.0.8)
Requirement already satisfied: importlib-metadata>=4.10.0 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from gym[accept-rom-license]) (4.12.0)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from gym[accept-rom-license]) (1.6.0)
Collecting autorom[accept-rom-license]~=0.4.2
  Downloading http://mirrors.aliyun.com/pypi/packages/83/aa/e2695fa0c93b39cfe2065fcd189e7eb2db88f6e0922e932fc615827070da/AutoROM-0.4.2-py3-none-any.whl (16 kB)
Requirement already satisfied: requests in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (2.28.1)
Requirement already satisfied: tqdm in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from 
autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (4.61.1)
Requirement already satisfied: click in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (8.0.0)
Collecting AutoROM.accept-rom-license
  Downloading http://mirrors.aliyun.com/pypi/packages/da/7e/7207e22fa5d7c37d2e15b69ed3fc0890fa42bc447e18d556ba0e3122dc75/AutoROM.accept-rom-license-0.5.0.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: zipp>=0.5 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from importlib-metadata>=4.10.0->gym[accept-rom-license]) (3.8.1)
Collecting libtorrent
  Using cached http://mirrors.aliyun.com/pypi/packages/af/24/0da378c340c71a2c0dcbf0657420714f2330e9dc84c3aac4c3c64fed068d/libtorrent-2.0.7-cp39-cp39-win_amd64.whl (1.9 MB)
Requirement already satisfied: colorama in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from click->autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (0.4.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hasee\appdata\local\programs\python\python-3.9.13\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->gym[accept-rom-license]) (3.4)
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for AutoROM.accept-rom-license (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying AutoROM.py -> build\lib
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      copying build\lib\AutoROM.py -> build\bdist.win-amd64\wheel\.
      running install_egg_info
      running egg_info
      writing AutoROM.accept_rom_license.egg-info\PKG-INFO
      writing dependency_links to AutoROM.accept_rom_license.egg-info\dependency_links.txt
      writing requirements to AutoROM.accept_rom_license.egg-info\requires.txt
      writing top-level names to AutoROM.accept_rom_license.egg-info\top_level.txt
      reading manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      Copying AutoROM.accept_rom_license.egg-info to build\bdist.win-amd64\wheel\.\AutoROM.accept_rom_license-0.5.0-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\__init__.py", 
line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\hasee\AppData\Local\Temp\pip-build-env-_0ghicfd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 11, in run
        File "C:\Users\hasee\AppData\Local\Temp\pip-install-b46r99g6\autorom-accept-rom-license_3731ea820070489cb13bbb2cbd24cd32\AutoROM.py", line 13, in <module>
          import libtorrent as lt
      ImportError: DLL load failed while importing libtorrent: 找不到指定的模块。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects

**Comment by JesseFarebro** [comment]
Hi @xiezhipeng-git,

We don't maintain the AutoROM package. It seems you're having an issue with the pre-compiled libtorrent library they're using. It's best to open an issue in their repository as I'm not familiar with this implementation.
